<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
    <line>
      <![CDATA[Element doesn't exist]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="47343" started-at="2015-12-07T08:31:16Z" finished-at="2015-12-07T08:32:04Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="47343" started-at="2015-12-07T08:31:16Z" finished-at="2015-12-07T08:32:04Z">
      <class name="testsuite_Articles.TM_JOOMLA_ARTICLE_1to8">
        <test-method status="PASS" signature="Setup()[pri:0, instance:testsuite_Articles.TM_JOOMLA_ARTICLE_1to8@1f50bcc]" name="Setup" is-config="true" duration-ms="19723" started-at="2015-12-07T15:31:16Z" finished-at="2015-12-07T15:31:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method status="PASS" signature="TC_JOOMLA_ARTICLE_001()[pri:0, instance:testsuite_Articles.TM_JOOMLA_ARTICLE_1to8@1f50bcc]" name="TC_JOOMLA_ARTICLE_001" duration-ms="16247" started-at="2015-12-07T15:31:36Z" finished-at="2015-12-07T15:31:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_JOOMLA_ARTICLE_001 -->
        <test-method status="PASS" signature="TC_JOOMLA_ARTICLE_002()[pri:0, instance:testsuite_Articles.TM_JOOMLA_ARTICLE_1to8@1f50bcc]" name="TC_JOOMLA_ARTICLE_002" duration-ms="7489" started-at="2015-12-07T15:31:52Z" finished-at="2015-12-07T15:32:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_JOOMLA_ARTICLE_002 -->
        <test-method status="FAIL" signature="TC_JOOMLA_ARTICLE_003()[pri:0, instance:testsuite_Articles.TM_JOOMLA_ARTICLE_1to8@1f50bcc]" name="TC_JOOMLA_ARTICLE_003" duration-ms="2846" started-at="2015-12-07T15:32:00Z" finished-at="2015-12-07T15:32:03Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at commons.AutoElements.verifyTrue(AutoElements.java:114)
	at actions.ac_ArticlePage.checkArticlePublishStatus(ac_ArticlePage.java:82)
	at testsuite_Articles.TM_JOOMLA_ARTICLE_1to8.TC_JOOMLA_ARTICLE_003(TM_JOOMLA_ARTICLE_1to8.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Element doesn't exist]]>
            </line>
          </reporter-output>
        </test-method> <!-- TC_JOOMLA_ARTICLE_003 -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:testsuite_Articles.TM_JOOMLA_ARTICLE_1to8@1f50bcc]" name="teardown" is-config="true" duration-ms="1012" started-at="2015-12-07T15:32:03Z" finished-at="2015-12-07T15:32:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testsuite_Articles.TM_JOOMLA_ARTICLE_1to8 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
